export let style1 = [
	{ value: "red1", text: "紅配色" },
	{ value: "orange1", text: "橘配色" },
	{ value: "yellow1", text: "黃配色" },
	{ value: "green1", text: "綠配色" },
	{ value: "blue1", text: "藍配色" },
	{ value: "indigo1", text: "靛配色" },
	{ value: "purple1", text: "紫配色" },
	{ value: "grayscale1", text: "黑白灰配色" }
];
export let style2 = [
	{ value: "red2", text: "紅底" },
	{ value: "orange2", text: "橘底" },
	{ value: "yellow2", text: "黃底" },
	{ value: "green2", text: "綠底" },
	{ value: "blue2", text: "藍底" },
	{ value: "indigo2", text: "靛底" },
	{ value: "purple2", text: "紫底" },
	{ value: "grayscale2", text: "黑灰底" }
];

let red1 = {
	"--text": "#3a3a3a",
	"--bg": "#fff",
	"--link": "#8c4142",
	"--btnBg": "#8c4142",
	"--btnText": "#fff",
	"--hoverBg": "#e8d9d9",
	"--hoverText": "#fff",
	"--menu-border-color": "#8c4142",
	"--menu-sidebar-bg": "#e8d9d9",
	"--menu-sidebar-icon": "#8c4142",
	"--menu-sidebar-text": "#8c4142",
	"--menu-item-border-color": "#e8d9d9",
	"--menu-item-bg": "#ffffff",
	"--menu-item-text": "#8c4142",
	"--menu-top": "#8c4142",
	"--menu-box-shadow": "rgba(255,255,255,.6)"
};
let red2 = {
	"--text": "#fff",
	"--bg": "#8c4142",
	"--link": "#ffe26f",
	"--btnBg": "#fff",
	"--btnText": "#8c4142",
	"--hoverBg": "#703435)",
	"--hoverText": "#282828",
	"--menu-border-color": "#e8d9d9",
	"--menu-sidebar-bg": "#8c4142",
	"--menu-sidebar-icon": "#e8d9d9",
	"--menu-sidebar-text": "#fff",
	"--menu-item-border-color": "#8c4142",
	"--menu-item-bg": "#703435",
	"--menu-item-text": "#e8d9d9",
	"--menu-top": "#fff",
	"--menu-box-shadow": "rgba(0,0,0,.6)"
};

let orange1 = {
	"--text": "#3a3a3a",
	"--bg": "#fff",
	"--link": "#ec8d31",
	"--btnBg": "#ec8d31",
	"--btnText": "#fff",
	"--hoverBg": "#fbe8d6",
	"--hoverText": "#fff",
	"--menu-border-color": "#ec8d31",
	"--menu-sidebar-bg": "#feecdb",
	"--menu-sidebar-icon": "#ec8d31",
	"--menu-sidebar-text": "#ec8d31",
	"--menu-item-border-color": "#feecdb",
	"--menu-item-bg": "#fff",
	"--menu-item-text": "#ec8d31",
	"--menu-top": "#ec8d31",
	"--menu-box-shadow": "rgba(255,255,255,.6)"
};
let orange2 = {
	"--text": "#fff",
	"--bg": "#ec8d31",
	"--link": "#f6ff69",
	"--btnBg": "#fff",
	"--btnText": "#ff7200",
	"--hoverBg": "#bd7127",
	"--hoverText": "#282828",
	"--menu-border-color": "#fbe8d6",
	"--menu-sidebar-bg": "#ec8d31",
	"--menu-sidebar-icon": "#fbe8d6",
	"--menu-sidebar-text": "#ffffff",
	"--menu-item-border-color": "#ec8d31",
	"--menu-item-bg": "#bd7127",
	"--menu-item-text": "#fbe8d6",
	"--menu-top": "#ffffff",
	"--menu-box-shadow": "rgba(0,0,0,.6)"
};

let yellow1 = {
	"--text": "#3a3a3a",
	"--bg": "#fff",
	"--link": "#f8b300",
	"--btnBg": "#f8b300",
	"--btnText": "#fff",
	"--hoverBg": "#fef0cc",
	"--hoverText": "#fff",
	"--menu-border-color": "#f8b300",
	"--menu-sidebar-bg": "#fef0cc",
	"--menu-sidebar-icon": "#f8b300",
	"--menu-sidebar-text": "#f8b300",
	"--menu-item-border-color": "#fef0cc",
	"--menu-item-bg": "#ffffff",
	"--menu-item-text": "#f8b300",
	"--menu-top": "#f8b300",
	"--menu-box-shadow": "rgba(255,255,255,.6)"
};
let yellow2 = {
	"--text": "#3a3a3a",
	"--bg": "#f8b300",
	"--link": "#cc289c",
	"--btnBg": "#3a3a3a",
	"--btnText": "#ffffff",
	"--hoverBg": "#c68f00",
	"--hoverText": "#282828",
	"--menu-border-color": "#fef0cc",
	"--menu-sidebar-bg": "#f8b300",
	"--menu-sidebar-icon": "#fef0cc",
	"--menu-sidebar-text": "#3a3a3a",
	"--menu-item-border-color": "#f8b300",
	"--menu-item-bg": "#c68f00",
	"--menu-item-text": "#fef1cc",
	"--menu-top": "#ffffff",
	"--menu-box-shadow": "rgba(0,0,0,.6)"
};
let green1 = {
	"--text": "#3a3a3a",
	"--bg": "#fff",
	"--link": "#6cc05c",
	"--btnBg": "#6cc05c",
	"--btnText": "#fff",
	"--hoverBg": "#e2f2de",
	"--hoverText": "#fff",
	"--menu-border-color": "#6cc05c",
	"--menu-sidebar-bg": "#e2f2de",
	"--menu-sidebar-icon": "#6cc05c",
	"--menu-sidebar-text": "#6cc05c",
	"--menu-item-border-color": "#e2f2de",
	"--menu-item-bg": "#ffffff",
	"--menu-item-text": "#6cc05c",
	"--menu-top": "#6cc05c",
	"--menu-box-shadow": "rgba(255,255,255,.6)"
};
let green2 = {
	"--text": "#fff",
	"--bg": "#6cc05c",
	"--link": "#fffd4c",
	"--btnBg": "#fff",
	"--btnText": "#6ab751",
	"--hoverBg": "#569a4a",
	"--hoverText": "#282828",
	"--menu-border-color": "#e2f2de",
	"--menu-sidebar-bg": "#6cc05c",
	"--menu-sidebar-icon": "#e2f2de",
	"--menu-sidebar-text": "#fff",
	"--menu-item-border-color": "#6cc05c",
	"--menu-item-bg": "#569a4a",
	"--menu-item-text": "#e2f2de",
	"--menu-top": "#ffffff",
	"--menu-box-shadow": "rgba(0,0,0,.6)"
};

let blue1 = {
	"--text": "#3a3a3a",
	"--bg": "#fff",
	"--link": "#5caec0",
	"--btnBg": "#5caec0",
	"--btnText": "#fff",
	"--hoverBg": "#deeff2",
	"--hoverText": "#fff",
	"--menu-border-color": "#5caec0",
	"--menu-sidebar-bg": "#deeff2",
	"--menu-sidebar-icon": "#5caec0",
	"--menu-sidebar-text": "#5caec0",
	"--menu-item-border-color": "#deeff2",
	"--menu-item-bg": "#ffffff",
	"--menu-item-text": "#5caec0",
	"--menu-top": "#5caec0",
	"--menu-box-shadow": "rgba(255,255,255,.6)"
};
let blue2 = {
	"--text": "#fff",
	"--bg": "#5caec0",
	"--link": "#fff600",
	"--btnBg": "#fff",
	"--btnText": "#5caec0",
	"--hoverBg": "#4a8b9a",
	"--hoverText": "#282828",
	"--menu-border-color": "#deeff2",
	"--menu-sidebar-bg": "#5caec0",
	"--menu-sidebar-icon": "#deeff2",
	"--menu-sidebar-text": "#fff",
	"--menu-item-border-color": "#5caec0",
	"--menu-item-bg": "#4a8b9a",
	"--menu-item-text": "#deeff2",
	"--menu-top": "#ffffff",
	"--menu-box-shadow": "rgba(0,0,0,.6)"
};
let indigo1 = {
	"--text": "#3a3a3a",
	"--bg": "#fff",
	"--link": "#6c91b4",
	"--btnBg": "#6c91b4",
	"--btnText": "#fff",
	"--hoverBg": "#e2e9f0",
	"--hoverText": "#fff",
	"--menu-border-color": "#6c91b4",
	"--menu-sidebar-bg": "#e2e9f0",
	"--menu-sidebar-icon": "#6c91b4",
	"--menu-sidebar-text": "#6c91b4",
	"--menu-item-border-color": "#e2e9f0",
	"--menu-item-bg": "#ffffff",
	"--menu-item-text": "#6c91b4",
	"--menu-top": "#6c91b4",
	"--menu-box-shadow": "rgba(255,255,255,.6)"
};
let indigo2 = {
	"--text": "#fff",
	"--bg": "#6c91b4",
	"--link": "#8ef200",
	"--btnBg": "#fff",
	"--btnText": "#6c91b4",
	"--hoverBg": "#567490",
	"--hoverText": "#282828",
	"--menu-border-color": "#e2e9f0",
	"--menu-sidebar-bg": "#6c91b4",
	"--menu-sidebar-icon": "#e2e9f0",
	"--menu-sidebar-text": "#fff",
	"--menu-item-border-color": "#6c91b4",
	"--menu-item-bg": "#567490",
	"--menu-item-text": "#e2e9f0",
	"--menu-top": "#ffffff",
	"--menu-box-shadow": "rgba(0,0,0,.6)"
};
let purple1 = {
	"--text": "#3a3a3a",
	"--bg": "#fff",
	"--link": "#6c689a",
	"--btnBg": "#6c689a",
	"--btnText": "#fff",
	"--hoverBg": "#e2e1eb",
	"--hoverText": "#fff",
	"--menu-border-color": "#6c689a",
	"--menu-sidebar-bg": "#e2e1eb",
	"--menu-sidebar-icon": "#6c689a",
	"--menu-sidebar-text": "#6c689a",
	"--menu-item-border-color": "#e2e1eb",
	"--menu-item-bg": "#ffffff",
	"--menu-item-text": "#6c689a",
	"--menu-top": "#6c689a",
	"--menu-box-shadow": "rgba(255,255,255,.6)"
};
let purple2 = {
	"--text": "#fff",
	"--bg": "#6c689a",
	"--link": "#ffd800",
	"--btnBg": "#fff",
	"--btnText": "#6c689a",
	"--hoverBg": "#56537b",
	"--hoverText": "#282828",
	"--menu-border-color": "#e2e1eb",
	"--menu-sidebar-bg": "#6c689a",
	"--menu-sidebar-icon": "#e2e1eb",
	"--menu-sidebar-text": "#fff",
	"--menu-item-border-color": "#6c689a",
	"--menu-item-bg": "#56537b",
	"--menu-item-text": "#e2e1eb",
	"--menu-top": "#ffffff",
	"--menu-box-shadow": "rgba(0,0,0,.6)"
};
let grayscale1 = {
	"--text": "#3a3a3a",
	"--bg": "#fff",
	"--link": "#505050",
	"--btnBg": "#505050",
	"--btnText": "#fff",
	"--hoverBg": "#dcdcdc",
	"--hoverText": "#fff",
	"--menu-border-color": "#505050",
	"--menu-sidebar-bg": "#dcdcdc",
	"--menu-sidebar-icon": "#505050",
	"--menu-sidebar-text": "#505050",
	"--menu-item-border-color": "#dcdcdc",
	"--menu-item-bg": "#ffffff",
	"--menu-item-text": "#505050",
	"--menu-top": "#505050",
	"--menu-box-shadow": "rgba(255,255,255,.6)"
};
let grayscale2 = {
	"--text": "#fff",
	"--bg": "#505050",
	"--link": "#ffd800",
	"--btnBg": "#fff",
	"--btnText": "#505050",
	"--hoverBg": "#404040",
	"--hoverText": "#282828",
	"--menu-border-color": "#dcdcdc",
	"--menu-sidebar-bg": "#505050",
	"--menu-sidebar-icon": "#dcdcdc",
	"--menu-sidebar-text": "#fff",
	"--menu-item-border-color": "#505050",
	"--menu-item-bg": "#404040",
	"--menu-item-text": "#dcdcdc",
	"--menu-top": "#ffffff",
	"--menu-box-shadow": "rgba(0,0,0,.6)"
};
export default { red1, red2, orange1, orange2, yellow1, yellow2, green1, green2, blue1, blue2, purple1, purple2, indigo1, indigo2, grayscale1, grayscale2 };
